package dev.cyclesrenderer.nativebridge;

import java.lang.foreign.MemoryLayout;

import static dev.cyclesrenderer.nativebridge.NativeBridge.DEVICE_UPDATE_PHASE_COUNT;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_DOUBLE;
import static java.lang.foreign.ValueLayout.JAVA_FLOAT;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/** Single source of truth for Java FFM layouts shared with the native bridge ABI. */
final class NativeLayouts {
    static final MemoryLayout CAMERA_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_LONG.withName("frame_id"),
            JAVA_INT.withName("viewport_width"),
            JAVA_INT.withName("viewport_height"),
            JAVA_DOUBLE.withName("position_x"),
            JAVA_DOUBLE.withName("position_y"),
            JAVA_DOUBLE.withName("position_z"),
            JAVA_FLOAT.withName("rotation_x"),
            JAVA_FLOAT.withName("rotation_y"),
            JAVA_FLOAT.withName("rotation_z"),
            JAVA_FLOAT.withName("rotation_w"),
            JAVA_FLOAT.withName("vertical_fov_radians"),
            JAVA_FLOAT.withName("depth_far"),
            JAVA_FLOAT.withName("focus_distance"),
            JAVA_INT.withName("flags"));
    static final MemoryLayout RESOURCES_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_INT.withName("origin_x"),
            JAVA_INT.withName("origin_y"),
            JAVA_INT.withName("origin_z"),
            JAVA_INT.withName("material_count"),
            JAVA_INT.withName("texture_count"),
            JAVA_INT.withName("texture_byte_count"),
            JAVA_INT.withName("reserved_0"),
            JAVA_INT.withName("reserved_1"),
            JAVA_INT.withName("reserved_2"),
            JAVA_INT.withName("reserved_3"));
    static final MemoryLayout SECTION_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_LONG.withName("section_id"),
            JAVA_INT.withName("origin_x"),
            JAVA_INT.withName("origin_y"),
            JAVA_INT.withName("origin_z"),
            JAVA_INT.withName("vertex_count"),
            JAVA_INT.withName("triangle_count"),
            JAVA_INT.withName("reserved_0"),
            JAVA_INT.withName("reserved_1"),
            JAVA_INT.withName("tail_padding"));
    static final MemoryLayout FRAME_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_LONG.withName("generation"),
            JAVA_INT.withName("pixel_byte_count"),
            JAVA_INT.withName("flags"),
            JAVA_INT.withName("sample_count"),
            JAVA_INT.withName("reserved"));
    static final MemoryLayout FRAME_VIEW_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_LONG.withName("generation"),
            JAVA_INT.withName("sample_count"),
            JAVA_INT.withName("pixel_format"),
            JAVA_LONG.withName("pixel_byte_count"),
            JAVA_LONG.withName("token"),
            ADDRESS.withName("pixels"),
            JAVA_INT.withName("flags"),
            JAVA_INT.withName("reserved_0"),
            JAVA_INT.withName("reserved_1"),
            JAVA_INT.withName("reserved_2"));
    static final MemoryLayout SETTINGS_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_LONG.withName("revision"),
            JAVA_INT.withName("device_policy"),
            JAVA_INT.withName("resolution_mode"),
            JAVA_INT.withName("render_width"),
            JAVA_INT.withName("render_height"),
            JAVA_INT.withName("resolution_percentage"),
            JAVA_INT.withName("interactive_samples"),
            JAVA_INT.withName("still_samples"),
            JAVA_INT.withName("stationary_delay_millis"),
            JAVA_INT.withName("adaptive_sampling"),
            JAVA_INT.withName("minimum_samples"),
            JAVA_FLOAT.withName("noise_threshold"),
            JAVA_INT.withName("interactive_time_limit_millis"),
            JAVA_INT.withName("still_time_limit_millis"),
            JAVA_INT.withName("minimum_bounce"),
            JAVA_INT.withName("maximum_bounce"),
            JAVA_INT.withName("diffuse_bounces"),
            JAVA_INT.withName("glossy_bounces"),
            JAVA_INT.withName("transmission_bounces"),
            JAVA_INT.withName("volume_bounces"),
            JAVA_INT.withName("transparent_bounces"),
            JAVA_FLOAT.withName("clamp_direct"),
            JAVA_FLOAT.withName("clamp_indirect"),
            JAVA_FLOAT.withName("filter_glossy"),
            JAVA_INT.withName("reflective_caustics"),
            JAVA_INT.withName("refractive_caustics"),
            JAVA_INT.withName("pixel_filter"),
            JAVA_FLOAT.withName("filter_width"),
            JAVA_INT.withName("seed"),
            JAVA_INT.withName("denoiser_mode"),
            JAVA_INT.withName("denoiser_start_sample"),
            JAVA_INT.withName("denoiser_input"),
            JAVA_INT.withName("denoiser_prefilter"),
            JAVA_INT.withName("denoiser_quality"),
            JAVA_INT.withName("denoiser_use_gpu"),
            JAVA_FLOAT.withName("exposure_ev"),
            JAVA_FLOAT.withName("gamma"),
            JAVA_INT.withName("view_transform"),
            JAVA_INT.withName("active_pass"),
            JAVA_INT.withName("debug_overlay"),
            JAVA_INT.withName("dynamic_resolution"),
            JAVA_INT.withName("interactive_resolution_percentage"),
            JAVA_INT.withName("pass_cache_megabytes"),
            JAVA_INT.withName("sampling_pattern"),
            JAVA_FLOAT.withName("camera_clip_near"),
            JAVA_FLOAT.withName("camera_clip_far"),
            JAVA_INT.withName("projection_mode"),
            JAVA_FLOAT.withName("focal_length_mm"),
            JAVA_FLOAT.withName("sensor_width_mm"),
            JAVA_INT.withName("depth_of_field"),
            JAVA_FLOAT.withName("focus_distance"),
            JAVA_FLOAT.withName("f_stop"),
            JAVA_INT.withName("aperture_blades"),
            JAVA_FLOAT.withName("aperture_rotation_degrees"),
            JAVA_FLOAT.withName("aperture_ratio"),
            JAVA_INT.withName("atmosphere_sun_disc"),
            JAVA_FLOAT.withName("atmosphere_sun_size_degrees"),
            JAVA_FLOAT.withName("atmosphere_sun_intensity"),
            JAVA_FLOAT.withName("atmosphere_sun_elevation_degrees"),
            JAVA_FLOAT.withName("atmosphere_sun_rotation_degrees"),
            JAVA_FLOAT.withName("atmosphere_altitude_meters"),
            JAVA_FLOAT.withName("atmosphere_air_density"),
            JAVA_FLOAT.withName("atmosphere_aerosol_density"),
            JAVA_FLOAT.withName("atmosphere_ozone_density"),
            JAVA_FLOAT.withName("pbr_normal_strength"),
            JAVA_FLOAT.withName("pbr_emission_scale"),
            JAVA_INT.withName("working_space"),
            JAVA_INT.withName("dlss_quality_mode"),
            JAVA_INT.withName("depth_of_field_mode"),
            JAVA_INT.withName("camera_type"),
            JAVA_INT.withName("panorama_type"),
            JAVA_FLOAT.withName("fisheye_fov_degrees"),
            JAVA_FLOAT.withName("fisheye_lens_mm"),
            JAVA_FLOAT.withName("latitude_min_degrees"),
            JAVA_FLOAT.withName("latitude_max_degrees"),
            JAVA_FLOAT.withName("longitude_min_degrees"),
            JAVA_FLOAT.withName("longitude_max_degrees"),
            JAVA_FLOAT.withName("fisheye_polynomial_k0"),
            JAVA_FLOAT.withName("fisheye_polynomial_k1"),
            JAVA_FLOAT.withName("fisheye_polynomial_k2"),
            JAVA_FLOAT.withName("fisheye_polynomial_k3"),
            JAVA_FLOAT.withName("fisheye_polynomial_k4"),
            JAVA_FLOAT.withName("central_cylindrical_longitude_min_degrees"),
            JAVA_FLOAT.withName("central_cylindrical_longitude_max_degrees"),
            JAVA_FLOAT.withName("central_cylindrical_height_min"),
            JAVA_FLOAT.withName("central_cylindrical_height_max"),
            JAVA_FLOAT.withName("central_cylindrical_radius"),
            JAVA_FLOAT.withName("camera_shift_x"),
            JAVA_FLOAT.withName("camera_shift_y"),
            JAVA_FLOAT.withName("pbr_wetness"),
            JAVA_FLOAT.withName("pbr_subsurface_scale"),
            JAVA_FLOAT.withName("pbr_height_strength"),
            JAVA_FLOAT.withName("pbr_height_distance"),
            JAVA_INT.withName("pbr_height_mapping_mode"),
            JAVA_INT.withName("pbr_parallax_steps"));
    static final MemoryLayout PASS_DESCRIPTOR_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_INT.withName("pass_id"),
            JAVA_INT.withName("source_component_count"),
            JAVA_INT.withName("display_component_count"),
            JAVA_INT.withName("pixel_format"),
            JAVA_INT.withName("semantic"),
            JAVA_INT.withName("flags"),
            MemoryLayout.sequenceLayout(8, JAVA_INT).withName("reserved"));
    static final MemoryLayout CAPABILITIES_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_LONG.withName("capability_flags"),
            JAVA_LONG.withName("pass_mask"),
            JAVA_INT.withName("denoiser_mask"),
            JAVA_INT.withName("device_mask"),
            JAVA_INT.withName("maximum_width"),
            JAVA_INT.withName("maximum_height"),
            JAVA_INT.withName("device_count"),
            JAVA_INT.withName("color_transform_mask"),
            JAVA_INT.withName("color_lut_edge_length"),
            JAVA_INT.withName("color_lut_pixel_format"),
            JAVA_INT.withName("color_config_state"),
            JAVA_INT.withName("reserved"));
    static final MemoryLayout COLOR_LUT_DESCRIPTOR_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_INT.withName("view_transform"),
            JAVA_INT.withName("edge_length"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("pixel_format"),
            JAVA_INT.withName("flags"),
            JAVA_LONG.withName("pixel_byte_count"),
            JAVA_FLOAT.withName("shaper_log2_min"),
            JAVA_FLOAT.withName("shaper_log2_max"),
            JAVA_FLOAT.withName("shaper_epsilon"),
            JAVA_INT.withName("interpolation"),
            JAVA_INT.withName("color_look"),
            JAVA_INT.withName("working_space"),
            JAVA_INT.withName("display_device"),
            JAVA_INT.withName("reserved"));
    static final MemoryLayout DIAGNOSTICS_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("struct_size"),
            JAVA_INT.withName("struct_version"),
            JAVA_LONG.withName("settings_revision"),
            JAVA_LONG.withName("scene_revision"),
            JAVA_LONG.withName("camera_revision"),
            JAVA_LONG.withName("frame_generation"),
            JAVA_INT.withName("state_code"),
            JAVA_INT.withName("device_type"),
            JAVA_INT.withName("effective_denoiser"),
            JAVA_INT.withName("active_pass"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("sample_count"),
            JAVA_INT.withName("section_count"),
            JAVA_INT.withName("reset_level"),
            JAVA_INT.withName("frame_ready"),
            JAVA_INT.withName("active_frame_leases"),
            JAVA_INT.withName("peak_frame_leases"),
            JAVA_INT.withName("frame_slot_count"),
            JAVA_INT.withName("dropped_display_updates"),
            JAVA_INT.withName("target_sample_count"),
            JAVA_INT.withName("sampling_state"),
            JAVA_FLOAT.withName("sample_rate"),
            JAVA_INT.withName("settling_remaining_millis"),
            JAVA_LONG.withName("produced_frame_count"),
            JAVA_LONG.withName("copied_frame_count"),
            JAVA_LONG.withName("copied_byte_count"),
            JAVA_LONG.withName("unchanged_poll_count"),
            JAVA_INT.withName("last_convert_micros"),
            JAVA_INT.withName("ema_convert_micros"),
            JAVA_INT.withName("max_convert_micros"),
            JAVA_INT.withName("last_copy_micros"),
            JAVA_INT.withName("ema_copy_micros"),
            JAVA_INT.withName("max_copy_micros"),
            JAVA_INT.withName("frame_age_micros"),
            JAVA_INT.withName("sampling_transition_count"),
            JAVA_LONG.withName("scene_commit_count"),
            JAVA_LONG.withName("scene_delta_count"),
            JAVA_LONG.withName("render_start_count"),
            JAVA_INT.withName("last_scene_commit_micros"),
            JAVA_INT.withName("ema_scene_commit_micros"),
            JAVA_INT.withName("max_scene_commit_micros"),
            JAVA_INT.withName("last_scene_delta_micros"),
            JAVA_INT.withName("ema_scene_delta_micros"),
            JAVA_INT.withName("max_scene_delta_micros"),
            JAVA_INT.withName("last_render_start_micros"),
            JAVA_INT.withName("ema_render_start_micros"),
            JAVA_INT.withName("max_render_start_micros"),
            JAVA_INT.withName("frame_pixel_format"),
            JAVA_LONG.withName("cached_raw_pass_mask"),
            JAVA_LONG.withName("cached_denoised_pass_mask"),
            JAVA_LONG.withName("pass_cache_bytes"),
            JAVA_LONG.withName("pass_cache_budget_bytes"),
            JAVA_INT.withName("pass_cache_entry_count"),
            JAVA_INT.withName("pass_cache_eviction_count"),
            JAVA_INT.withName("pass_cache_hit_count"),
            JAVA_INT.withName("active_frame_variant"),
            JAVA_LONG.withName("registered_pass_mask"),
            JAVA_INT.withName("pass_registry_rebuild_count"),
            JAVA_INT.withName("pass_registry_hit_count"),
            JAVA_INT.withName("selected_denoiser"),
            JAVA_INT.withName("denoiser_scheduled"),
            JAVA_INT.withName("effective_denoiser_start_sample"),
            JAVA_INT.withName("denoiser_schedule_reason"),
            JAVA_INT.withName("denoiser_schedule_run_count"),
            JAVA_INT.withName("denoiser_schedule_skip_count"),
            JAVA_INT.withName("sampling_pattern"),
            JAVA_FLOAT.withName("effective_camera_clip_near"),
            JAVA_FLOAT.withName("effective_camera_clip_far"),
            JAVA_INT.withName("projection_mode"),
            JAVA_FLOAT.withName("vertical_fov_radians"),
            JAVA_INT.withName("depth_of_field"),
            JAVA_FLOAT.withName("focus_distance"),
            JAVA_FLOAT.withName("f_stop"),
            JAVA_FLOAT.withName("aperture_size"),
            JAVA_INT.withName("aperture_blades"),
            JAVA_FLOAT.withName("aperture_rotation_radians"),
            JAVA_FLOAT.withName("aperture_ratio"),
            JAVA_INT.withName("device_uuid_valid"),
            MemoryLayout.sequenceLayout(16, JAVA_BYTE).withName("device_uuid"),
            JAVA_INT.withName("reserved"),
            JAVA_LONG.withName("scene_timing_revision"),
            JAVA_LONG.withName("scene_timing_count"),
            JAVA_INT.withName("last_scene_queue_micros"),
            JAVA_INT.withName("ema_scene_queue_micros"),
            JAVA_INT.withName("max_scene_queue_micros"),
            JAVA_INT.withName("last_reset_wait_micros"),
            JAVA_INT.withName("ema_reset_wait_micros"),
            JAVA_INT.withName("max_reset_wait_micros"),
            JAVA_INT.withName("last_device_update_micros"),
            JAVA_INT.withName("ema_device_update_micros"),
            JAVA_INT.withName("max_device_update_micros"),
            JAVA_INT.withName("last_geometry_update_micros"),
            JAVA_INT.withName("ema_geometry_update_micros"),
            JAVA_INT.withName("max_geometry_update_micros"),
            JAVA_INT.withName("last_bvh_update_micros"),
            JAVA_INT.withName("ema_bvh_update_micros"),
            JAVA_INT.withName("max_bvh_update_micros"),
            JAVA_INT.withName("phase_reserved_0"),
            JAVA_INT.withName("phase_reserved_1"),
            JAVA_INT.withName("phase_reserved_2"),
            JAVA_INT.withName("last_scene_first_frame_micros"),
            JAVA_INT.withName("ema_scene_first_frame_micros"),
            JAVA_INT.withName("max_scene_first_frame_micros"),
            JAVA_INT.withName("timing_reserved"),
            JAVA_INT.withName("camera_type"),
            JAVA_INT.withName("panorama_type"),
            JAVA_INT.withName("active_device_phase"),
            JAVA_INT.withName("active_device_phase_micros"),
            MemoryLayout.sequenceLayout(
                    DEVICE_UPDATE_PHASE_COUNT, JAVA_INT).withName("last_device_phase_micros"),
            MemoryLayout.sequenceLayout(
                    DEVICE_UPDATE_PHASE_COUNT, JAVA_INT).withName("ema_device_phase_micros"),
            MemoryLayout.sequenceLayout(
                    DEVICE_UPDATE_PHASE_COUNT, JAVA_INT).withName("max_device_phase_micros"),
            JAVA_FLOAT.withName("camera_shift_x"),
            JAVA_FLOAT.withName("camera_shift_y"),
            JAVA_INT.withName("last_render_configure_micros"),
            JAVA_INT.withName("ema_render_configure_micros"),
            JAVA_INT.withName("max_render_configure_micros"),
            JAVA_INT.withName("last_render_reset_micros"),
            JAVA_INT.withName("ema_render_reset_micros"),
            JAVA_INT.withName("max_render_reset_micros"),
            JAVA_INT.withName("last_render_prepare_micros"),
            JAVA_INT.withName("ema_render_prepare_micros"),
            JAVA_INT.withName("max_render_prepare_micros"),
            JAVA_INT.withName("last_session_start_micros"),
            JAVA_INT.withName("ema_session_start_micros"),
            JAVA_INT.withName("max_session_start_micros"));
    static final MemoryLayout VULKAN_INTEROP_BUFFER_LAYOUT =
            MemoryLayout.structLayout(
                    JAVA_INT.withName("struct_size"),
                    JAVA_INT.withName("struct_version"),
                    JAVA_INT.withName("width"),
                    JAVA_INT.withName("height"),
                    JAVA_INT.withName("pixel_format"),
                    JAVA_INT.withName("flags"),
                    JAVA_LONG.withName("allocation_byte_count"),
                    JAVA_LONG.withName("memory_handle"),
                    MemoryLayout.sequenceLayout(16, JAVA_BYTE).withName("device_uuid"),
                    JAVA_INT.withName("slot_count"),
                    JAVA_INT.withName("slot_stride_bytes"),
                    JAVA_LONG.withName("ready_semaphore_handle"),
                    JAVA_LONG.withName("release_semaphore_handle"));
    static final MemoryLayout VERTEX_LAYOUT = MemoryLayout.structLayout(
            JAVA_FLOAT.withName("position_x"),
            JAVA_FLOAT.withName("position_y"),
            JAVA_FLOAT.withName("position_z"),
            JAVA_FLOAT.withName("normal_x"),
            JAVA_FLOAT.withName("normal_y"),
            JAVA_FLOAT.withName("normal_z"),
            JAVA_FLOAT.withName("texture_u"),
            JAVA_FLOAT.withName("texture_v"),
            JAVA_INT.withName("packed_rgba"),
            JAVA_INT.withName("reserved"));
    static final MemoryLayout TRIANGLE_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("vertex_0"),
            JAVA_INT.withName("vertex_1"),
            JAVA_INT.withName("vertex_2"),
            JAVA_INT.withName("material_index"));
    static final MemoryLayout MATERIAL_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("texture_index"),
            JAVA_INT.withName("flags"),
            JAVA_FLOAT.withName("emission_strength"),
            JAVA_FLOAT.withName("alpha_cutoff"),
            JAVA_INT.withName("normal_texture_index"),
            JAVA_INT.withName("material_texture_index"),
            JAVA_INT.withName("pbr_format"),
            JAVA_INT.withName("auxiliary_texture_index"));
    static final MemoryLayout TEXTURE_LAYOUT = MemoryLayout.structLayout(
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("pixel_offset"),
            JAVA_INT.withName("pixel_size"),
            JAVA_INT.withName("role"),
            JAVA_INT.withName("reserved_1"),
            JAVA_INT.withName("reserved_2"),
            JAVA_INT.withName("reserved_3"));
    static final MemoryLayout TEXTURE_REGION_UPDATE_LAYOUT = TextureRegionUpdateAbi.LAYOUT;

    static {
        if (CAMERA_LAYOUT.byteSize() != 80L
                || RESOURCES_LAYOUT.byteSize() != 48L
                || SECTION_LAYOUT.byteSize() != 48L
                || FRAME_LAYOUT.byteSize() != 40L
                || FRAME_VIEW_LAYOUT.byteSize() != 72L
                || SETTINGS_LAYOUT.byteSize() != 392L
                || PASS_DESCRIPTOR_LAYOUT.byteSize() != 64L
                || CAPABILITIES_LAYOUT.byteSize() != 64L
                || COLOR_LUT_DESCRIPTOR_LAYOUT.byteSize() != 72L
                || DIAGNOSTICS_LAYOUT.byteSize() != 672L
                || VULKAN_INTEROP_BUFFER_LAYOUT.byteSize() != 80L
                || VulkanInteropStateAbi.LAYOUT.byteSize()
                        != VulkanInteropStateAbi.BYTE_SIZE
                || VERTEX_LAYOUT.byteSize() != 40L
                || TRIANGLE_LAYOUT.byteSize() != 16L
                || MATERIAL_LAYOUT.byteSize() != 32L
                || TEXTURE_LAYOUT.byteSize() != 32L
                || TEXTURE_REGION_UPDATE_LAYOUT.byteSize()
                        != TextureRegionUpdateAbi.BYTE_SIZE) {
            throw new ExceptionInInitializerError("native bridge structure layout mismatch");
        }
    }

    static void validate() {
        // Class initialization performs the layout assertions above.
    }

    private NativeLayouts() {
    }
}
